/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Azure;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import static java.lang.Integer.max;
import static java.lang.Integer.min;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.Spring.max;

/**
 *
 * @author Robert Donnan
 */
public class LoginPage extends javax.swing.JFrame {

    
Connection con;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        otpnumbertxt = new javax.swing.JTextField();
        numbertxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Login Form");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("User Name");

        usernametxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/custom_resized_3d0589ab-3598-4b5c-a1eb-1b9f901eade8 (1).png"))); // NOI18N
        jLabel13.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2)
                .addGap(84, 84, 84)
                .addComponent(usernametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(147, 147, 147))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        passwordtxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        loginbtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        cancelbtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Number");

        numbtn.setText("Get passcode ");
        numbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Enter One time passcode sent via SMS");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("One time passcode");

        otpnumbertxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        otpnumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpnumbertxtActionPerformed(evt);
            }
        });

        numbertxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        numbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbertxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(127, 127, 127))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(86, 86, 86))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(loginbtn)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(numbertxt)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(57, 57, 57)
                        .addComponent(otpnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(numbtn)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numbtn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(numbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(otpnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn)
                    .addComponent(cancelbtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(641, 418));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed
public class HashandSaltPass {
//private static final int SALT_LGTH = 16;

  /** private static byte[] generateSalt(){
        SecureRandom rd = new SecureRandom();
        byte[] salt = new byte[SALT_LGTH];
        rd.nextBytes(salt);
        return salt;
    }**/
//NoSuchAlgorithmException used if algorithm isn't available such as bcrypt
    public static String hashPassword(String pass, String salt) throws NoSuchAlgorithmException {
      //  byte[] saltByte = pass.getBytes();
       // byte[] passwordByte = pass.getBytes();

    MessageDigest md = MessageDigest.getInstance("sha512");//algorithm used 
   // md.update(passwordByte);
   // md.update(saltByte);
    
    byte[] hashInBytes = md.digest(pass.getBytes(StandardCharsets.UTF_8));//Specifies charset 
   

    StringBuilder sb = new StringBuilder();
    for (byte b : hashInBytes) {
        sb.append(String.format("%02x", b));//formats password
    }
    return sb.toString();
}
 
}  
       
    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
      //gets text and stores as string
      //variables with 'sanitised' refer to variables that replace all sql commands 
        String uname = usernametxt.getText();
        String sanitiseduname = uname.replaceAll("select|insert|update|delete|truncate", "");
       String pword = passwordtxt.getText();
       String sanitisedpword = pword.replaceAll("select|insert|update|delete|truncate", "");
       String num = numbertxt.getText();
       String sanitisednum = num.replaceAll("select|insert|update|delete|truncate", "");
       String otp = otpnumbertxt.getText();
       String sanitisedotp = otp.replaceAll("select|insert|update|delete|truncate", "");
       String otpstr = String.valueOf(otpnum);
           con = Connections.getConnection();//Connection to database
    try {
        pst = con.prepareStatement("insert into Passcode (OtpNum) values (?)");
        pst.setString(1, otpstr);
        pst.execute();
    } catch (SQLException ex) {
        Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
    }
      
      
       //if statement that validates login from the database connection 
       if(uname.equals("")||pword.equals("")||num.equals("")||otp.equals((""))){
           JOptionPane.showMessageDialog(rootPane,"One or multiple boxes are empty", 
                   "Please check all boxes",1);
       }else{
        try{
            con = Connections.getConnection();//connection object
            PreparedStatement pst = con.prepareStatement("Select * FROM Login Where username = ? and password = ? and Number = ?");
            
           // byte[] salt = Register.HashandSaltPass.generateSalt();
          //stores password as a string in the database 
              //  String hashedPassword = Register.HashandSaltPass.hashPassword(sanitisedpword, new String(salt)); 
              String hashedPassword = Register.hashPassword(sanitisedpword); 
            pst.setString(1, uname);
            pst.setString(2, hashedPassword);
            pst.setString(3, num);
            ResultSet rs = pst.executeQuery();
//gets data inside database to ensure number is correct. In this case the number would be given to the user via text and if they enter the right number they can login 
           PreparedStatement pst2 = con.prepareStatement("SELECT * FROM Passcode WHERE OtpNum = ?");
           pst2.setString(1, otp);//otp refers to one time passcode, this is needed by the user for second verification
           ResultSet rs2 = pst2.executeQuery();

           //if user one time passcode and login details are correct, welcome screen appears 
if (rs2.next()) {
       if(rs.next()){
                String dbusername = rs.getString("username");//username displays on screen
                Welcome welcome = new Welcome(dbusername);
                welcome.setVisible(true);
                setVisible(false);
            }
    } else {
      JOptionPane.showMessageDialog(rootPane, "Check the passcode sent via text and enter it to login. ", "Wrong passcode entered", 1);
    }
        }catch (Exception Ex){
            System.out.println("An error occurred"+Ex);
        }
        con = Connections.getConnection();//connection obj
       }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        ClearFields();
    }//GEN-LAST:event_cancelbtnActionPerformed

    public int otpnum;
      
    private void numbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtnActionPerformed
        // TODO add your handling code here:
            // This URL is used for sending messages
        String myURI = "https://api.bulksms.com/v1/messages";
        // change these values to match your own account
        String myUsername = "robertdonnan38";
        String myPassword = ".g72E6hyD.a9zcp";
        Random random = new Random();
        int min = 1000;
        int max = 9999;
       otpnum = random.nextInt((max-min + min));
        String number = numbertxt.getText();
        // the details of the message we want to send
        String myData = "{to: \""+number+"\", body: \"OTP number is :" + otpnum + "\"}";
        // build the request based on the supplied settings
        URL url = null;
        try {
            url = new URL(myURI);
        } catch (MalformedURLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        HttpURLConnection request;
        try {
            request = (HttpURLConnection) url.openConnection();
            request.setDoOutput(true);
            // supply the credentials
            String authStr = myUsername + ":" + myPassword;
            String authEncoded = Base64.getEncoder().encodeToString(authStr.getBytes());
            request.setRequestProperty("Authorization", "Basic " + authEncoded);
            // we want to use HTTP POST
            request.setRequestMethod("POST");
            request.setRequestProperty( "Content-Type", "application/json");
            try ( // write the data to the request
                    OutputStreamWriter out = new OutputStreamWriter(request.getOutputStream())) {
                out.write(myData);
            }
            // try ... catch to handle errors
            try {
                // make the call to the API
                InputStream response = request.getInputStream();
                try (BufferedReader in = new BufferedReader(new InputStreamReader(response))) {
                    String replyText;
                    while ((replyText = in.readLine()) != null) {
                        System.out.println(replyText);
                    }
                }
            } catch (IOException ex) {
                System.out.println("An error occurred:" + ex.getMessage());
                // print the detail that comes with the error
                try (BufferedReader in = new BufferedReader(new InputStreamReader(request.getErrorStream()))) {
                    // print the detail that comes with the error
                    String replyText;
                    while ((replyText = in.readLine()) != null) {
                        System.out.println(replyText);
                    }
                }
            }
            request.disconnect();
        } catch (IOException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
      
    }//GEN-LAST:event_numbtnActionPerformed

    private void otpnumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpnumbertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpnumbertxtActionPerformed

    private void numbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbertxtActionPerformed

     public void ClearFields(){
         //clears text when button is clicked
            usernametxt.setText("");
            passwordtxt.setText("");
           
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField numbertxt;
    private javax.swing.JButton numbtn;
    private javax.swing.JTextField otpnumbertxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
